### ISSUE TITLE
[Bug]: Maximum call stack size of 8355840 bytes (zend.max_allowed_stack_size - zend.reserved_stack_size) reached. Infinite recursion?

### ISSUE THREAD

**Issue by guanguans** [Laravel-Lang/common#199]
### Lang Package Name

laravel-lang/routes

### Lang Package Version

1.4.0

### Laravel Framework Version

10.48.16

### PHP Version

8.\*.\*

## In the PHP 8.1 and 8.2

```shell
php81 artisan
                                                                                                                                                          
[1]    32667 segmentation fault  /opt/homebrew/opt/php@8.1/bin/php artisan
```

## In the PHP 8.3

```shell
╰─ php83 artisan                                                                                                                                              ─╯

   Error 

  Maximum call stack size of 8355840 bytes (zend.max_allowed_stack_size - zend.reserved_stack_size) reached. Infinite recursion?

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:1322
    1318▕      *
    1319▕      * @param  string  $abstract
    1320▕      * @return string
    1321▕      */
  ➜ 1322▕     public function getAlias($abstract)
    1323▕     {
    1324▕         return isset($this->aliases[$abstract])
    1325▕                     ? $this->getAlias($this->aliases[$abstract])
    1326▕                     : $abstract;

      +46582 vendor frames 

  46583[internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(LaravelLang\Routes\ServiceProvider))
      +5 vendor frames 

  46589artisan:36
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```

### Steps to reproduce

```php
<?php

declare(strict_types=1);

namespace LaravelLang\Routes;

...

class ServiceProvider extends BaseServiceProvider
{
    ...
    protected function urlGenerator(): void
    {
        $this->app->singleton('url', function ($app) {
			...
            $app->instance('routes', $routes); // The problem(segmentation faul) caused by this line.
			...
        });
    }
    ...
}
```

**Comment by andrey-helldar** [comment]
This was an unobvious problem when trying to extend the functionality of the `route` function.

These changes were reversed in version [1.5](https://github.com/Laravel-Lang/routes/releases/tag/1.5.0) and instead added a new function - `localizedRoute` ([example](https://laravel-lang.com/packages-routes.html#via_localization_group)).

Thank you for report!

**Comment by alexey-m-ukolov** [comment]
@guanguans, can you please share your process of pinpointing the issue down to the service provider? All I was able to determine when faced with this error, is that it was a problem with the routes package.

**Comment by guanguans** [comment]
@alexey-m-ukolov

When I realized it was a `segmentation fault` error, my first thought was to run it with a different version of php. Found that it showed up as a normal error in a php 8.3 environment. Then went through the error log to locate the error line[#14 /.../vendor/laravel-lang/routes/src/ServiceProvider.php(33): Illuminate\\Container\\Container->instance('routes', Object(Illuminate\\Routing\\RouteCollection))]

```log
#7 /.../vendor/laravel/framework/src/Illuminate/Foundation/Application.php(961): Illuminate\\Container\\Container->resolve('url', Array, true)
#8 /.../vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve('url', Array)
#9 /.../vendor/laravel/framework/src/Illuminate/Foundation/Application.php(946): Illuminate\\Container\\Container->make('url', Array)
#10 /.../vendor/laravel/framework/src/Illuminate/Container/Container.php(1454): Illuminate\\Foundation\\Application->make('url')
#11 /.../vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(87): Illuminate\\Container\\Container->offsetGet('url')
#12 /.../vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\\Routing\\RoutingServiceProvider->Illuminate\\Routing\\{closure}(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Routing\\RouteCollection))
#13 /.../vendor/laravel/framework/src/Illuminate/Container/Container.php(481): Illuminate\\Container\\Container->rebound('routes')
#14 /.../vendor/laravel-lang/routes/src/ServiceProvider.php(33): Illuminate\\Container\\Container->instance('routes', Object(Illuminate\\Routing\\RouteCollection))
#15 /.../vendor/laravel/framework/src/Illuminate/Container/Container.php(908): LaravelLang\\Routes\\ServiceProvider->LaravelLang\\Routes\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#16 /.../vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build(Object(Closure))
```
